name: nexus_void_2089
description: A cyberpunk digital civilization portfolio
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # shaders:
  #   - shaders/void_warp.frag
  #   - shaders/hologram.frag
  #   - shaders/chromatic_aberration.frag
  #   - shaders/energy_field.frag

  # assets:
  #   - assets/rive/
  #   - assets/lottie/
  #   - assets/audio/
  #   - assets/images/